todo/todo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from main import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'todo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^tasks/(?P<task_id>\d+)/(?:(?P<action>\w+))?', views.taskView, name='task_view'),
    url(r'^tasks/(?P<action>add)', views.taskView, name='task_add'),
    url(r'^tasks/(?P<type>[^0-9]\w*)?', views.taskList, name='task_list'),
#    url(r'^tasks/', views.taskList, name='task_list'),
    url(r'^repeats/(?P<repeat_id>\d+)/(?:(?P<action>\w+))?', views.repeatView, name='repeat_view'),
    url(r'^repeats/(?P<action>add)', views.repeatView, name='repeat_add'),
    url(r'^repeats/', views.repeatList, name='repeat_list'),
    url(r'^schedules/modify.html', views.scheduleView, name='schedule_view'),
    url(r'^schedules/', views.scheduleList, name='schedule_list'),
    url(r'^statuses/', views.statusList, name='status_list'),
    url(r'^raw/', views.raw, name='raw'),
    url(r'^', views.taskList, name='task_list'),
)

todo/main/models.py
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
from calendar import monthrange
from math import ceil
from copy import deepcopy

from django.utils import timezone

from django.db import models
from django.db.models.signals import m2m_changed, post_save
from django.dispatch import receiver

class Repeat(models.Model):
    # year of -1 means ignore year of dates
    # year of 0 means dates with same year
    # year of n>0 means dates in year and every nth year after
    name = models.CharField('e.g. monthly', max_length=200, default='')
    day = models.IntegerField(default=-1)
    week = models.IntegerField(default=-1)
    month = models.IntegerField(default=-1)
    year = models.IntegerField(default=-1)

    def __unicode__(self):
        return self.name

class Schedule(models.Model):
    repeat = models.ForeignKey(Repeat)
    start_date = models.DateTimeField('Date from which to repeat')

    class Meta:
        ordering = ['repeat__year', 'repeat__month', 'repeat__week', 'repeat__day']

    def task_usage(self):
        return self.task_set.count()

    def __unicode__(self):
        r = self.repeat
        s = ''
        weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
        months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        def ord(n):
            a = n % 10
            x = 'th'
            if a == 1: x = 'st'
            if a == 2: x = 'nd'
            if a == 3: x = 'rd'
            return str(n) + x
        if r.day == 0:
            if r.week == 0:
                d = int(ceil(self.start_date.day/7.0))
                if d == 0: d = 1
                s += '%s %s ' % (ord(d), weekdays[(self.start_date.weekday()+1)%7])
            elif r.week > 0:
                if r.week == 1:
                    s += "%s every week" % weekdays[(self.start_date.weekday()+1)%7]
                else:
                    s += "%s every %d weeks" % (weekdays[(self.start_date.weekday()+1)%7], r.week)
            else:
                s += ord(self.start_date.day) + ' day'
        else:
            if r.day > 0:
                s += 'every %d days of' % r.day
            else:
#                s += 'all of'
                pass
            if r.week == 0:
                s += ' the %s week' % ord(ceil(self.start_date.day/7.0))
            elif r.week > 0:
                s += ' every %d weeks' % r.week
        if r.month == 0:
            s += ' of ' + months[self.start_date.month-1]
        elif r.month > 0:
            s += ' of '
            if 12 % r.month == 0:
                if r.month == 1:
                    s += 'the month'
                else:
                    for i in range(self.start_date.month-1, self.start_date.month+11, r.month):
                        s += months[i%12] + ','
                    s = s[:-1]
            else:
                s += 'every %d months' % r.month
        if r.year == 0:
            if len(s) == 0: s = 'all'
            s += ' of ' + str(self.start_date.year)
        elif r.year > 0:
            if r.year == 1:
                s += ' every year'
            else:
                s += ' of every %d years' % r.year
        s += ' starting ' + self.start_date.strftime('%Y-%m-%d')
        return s


class Task(models.Model):
    name = models.CharField('Name of task', max_length=200)
    desc = models.TextField('What is involved', blank=True, default='')
    date_created = models.DateTimeField('Date created', default=timezone.now, blank=True)
    schedules = models.ManyToManyField(Schedule, blank=True)
    next_date = models.DateTimeField('Cached date of next occurance', default=timezone.now, blank=True)
    next_due = models.DateTimeField('Cached date of next time due after completion', default=timezone.now, blank=True)
    
    def is_due(self):
        return self.next_date < timezone.now()

    def is_onetime(self):
        return self.schedules.count() == 0

    def last_done(self):
        completions = self.status_set.filter(complete=True).order_by('-date')
        if completions.count() > 0:
            return completions[0].date
        else:
            return self.date_created
    
    def repeat_list_str(self):
        str = ''
        reps = Repeat.objects.filter(schedule__task=self).distinct()
        if reps.count() == 0:
            return None
        for repeat in reps:
            str += repeat.name + ','
        str = str[:-1]
        return str

    def next_scheduled_time(self):
        completions = self.status_set.filter(complete=True).order_by('-date')
        if completions.count() > 0:
            after = completions[0].date
        else:
            after = self.date_created
        return self.next_occurance_after(after)

    def next_occurance_after(self, after):
        schedules = self.schedules.all()
        # next_occurance keeps track of soonest date from any schedule so far
        next_occurance = timezone.make_aware(timezone.datetime.max, timezone.get_default_timezone())
        if after == self.date_created and schedules.count() == 0:
            # if this task is one-time and hasn't been completed
            # then set next_occurance to creation date so it shows as incomplete
            next_occurance = self.date_created
        for schedule in schedules:
            # The goal is to find the first occurrence of schedule after the date `after`
            # `last` gets pushed forward from start date to find last occurrence before `after`
            # `after` could be the last day done or today.  We want the first occurrence after it
            # `next` is the first occurrence after `after`
            # The order in history should be start_date..>>>last....after....next
            last = deepcopy(schedule.start_date)
            r = schedule.repeat
            last_unit = 'start'
            next = None
            if r.year > 0:
                years_to_now = relativedelta(after, last).years
                last += relativedelta(years=years_to_now - years_to_now % r.year)
                last_unit = 'year'
                next = last + relativedelta(years=r.year)
            if r.month > -1:
                if r.month > 0:
                    # relativedelta.months here doesn't account for several years between
                    months_to_now = (after.year-last.year)*12 + (after.month-last.month)
                    # account for when the months of the dates is 1 apart, but dates are more than a month apart
                    if after.day-last.day > monthrange(last.year, last.month)[1]:
                        months_to_now += 1
                    last += relativedelta(months=months_to_now - months_to_now % r.month)
                    t = last + relativedelta(months=r.month)
                    if (next == None or t < next):
                        next = t
                last_unit = 'month'
            if r.week > -1:
                if r.week > 0:
                    weeks_to_now = (after-last).days/7
                    last += relativedelta(weeks=weeks_to_now - weeks_to_now % r.week)
                    t = last + relativedelta(weeks=r.week)
                    if (next == None or t < next):
                        next = t
                else:
                    if last_unit == 'year':
                        # (last and next).isocalendar()[1] is week of year
                        last += relativedelta(weeks=last.isocalendar()[1]-schedule.start_date.isocalendar()[1])
                        next += relativedelta(weeks=next.isocalendar()[1]-schedule.start_date.isocalendar()[1])
                last_unit = 'week'
            if r.day > -1:
                if r.day > 0:
                    days_to_now = (after-last).days # relativedelta(datetime.now(), last).days
                    last += relativedelta(days=days_to_now - days_to_now % r.day)
                    t = last + relativedelta(days=r.day)
                    if (next == None or t < next):
                        next = t
                else:
                    if last_unit == 'week':
                        diff = schedule.start_date.weekday()-last.weekday()
                        if (last.day+diff < 1):
                            diff += 7;
                        last += relativedelta(days=diff)
                        diff = schedule.start_date.weekday()-next.weekday()
                        if (next.day+diff < 1):
                            diff += 7;
                        next += relativedelta(days=diff)
            if next == None: next = next_occurance
            if next < next_occurance:
                next_occurance = next
        return next_occurance
    
    def __unicode__(self):
        return self.name


class Status(models.Model):
    task = models.ForeignKey(Task)
    text = models.TextField('What happened', blank=True, default='')
    complete = models.BooleanField('Does it complete the task?', default=False)
    date = models.DateTimeField('Date of status', default=timezone.now, blank=True)


@receiver(m2m_changed, sender=Task.schedules.through)
@receiver(post_save, sender=Status)
@receiver(post_save, sender=Schedule)
def update_next_date(sender, **kwargs):
    if sender == Schedule:
        # update all statuses using this schedule
        tasks = kwargs['instance'].task_set.all()
    elif sender == Task.schedules.through:
        tasks = [kwargs['instance']]
        if not kwargs['action'] in ['post_add', 'post_remove', 'post_clear']:
            return
    else:
        tasks = [kwargs['instance'].task]
    for task in tasks:
        task.next_date = task.next_scheduled_time()
        try:
            task.next_due = task.next_occurance_after(task.next_date+timedelta(days=1))
        except OverflowError:
            task.next_due = task.next_date
        task.save()

todo/main/forms.py
from django import forms
from main.models import Task, Schedule, Repeat, Status
        
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['id', 'name', 'desc', 'date_created', 'schedules']
    id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    repeat = forms.ModelChoiceField(label="New Repeat by Type", queryset=Repeat.objects.all(), required=False)
    start_date = forms.DateField(label="New Repeat start date", required=False)

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['id', 'repeat', 'start_date']
    id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

class RepeatForm(forms.ModelForm):
    class Meta:
        model = Repeat
        fields = ['id', 'name', 'day', 'week', 'month', 'year']
    id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

class StatusFormBasic(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['text', 'complete', 'date', 'task']
        widgets = {
            'task': forms.HiddenInput()
        }
    def handleInput(self):
        if self.is_valid():
            instance = self.save()
            return "OK" + str(instance.id)
        else:
            return "IVForm" + ", ".join([str(f.errors)+','+f.name for f in self])

todo/main/templates/tasks/list.html
{% extends "base_generic.html" %}

{% block header %}
        <script type="text/javascript">
            $(function() {
                $("#itemList").delegate(".completeButton", "click", function (event) {
                    var row = $(this).parents("tr").first();

                    $("#completeDialog form")[0].reset();
                    $("#completeDialog form #id_task").val(row.attr("id"));
                    $("#completeDialog :input").prop("disabled", false);
                    $("#completeDialog").insertAfter(row).toggle();
                    event.stopPropagation();
                });
                $("#itemList").delegate("tr", "click", function (event) {
                    if (this.id != "completeDialog") $(this).toggleClass("highlighted");
                });
                $("body").delegate("#submitComplete", "click", function (event) {
                    $.post("due.html", $("#completeDialog form").serialize(), function (data) {
                        if (data.indexOf("OK") == 0) {
                            if ($("#completeDialog #id_complete").is(":checked")) {
                                $("tr#" + $("#completeDialog #id_task").val()).appendTo("#itemList");
                            }
                            $("#completeDialog :input").prop("disabled", false);
                            $("#completeDialog").hide();
                        } else {
                            alert("Invalid information!");
                        }
                    });
                    $("#completeDialog :input").prop("disabled", true);
                    event.preventDefault();
                });
                $(".delButton").each(function(i, el) {
                    // change these links to use javascript
                    // this keeps it working if the browser doesn't support JS
                    $(el).data("url", el.href);
                    el.href = "javascript:void(null)";
                });
                $("body").delegate(".delButton", "click", function (event) {
                    name = $(this).parents("tr").find(".nameSpan").html();
                    if (confirm("Are you sure you want to delete " + name + "?")) {
                        window.location.href = $(this).data("url");
                    }
                });
            });
        </script>
        <style type="text/css">
            #completeDialog td {
                background-color: lightgrey;
                padding: 10px 5px;
            }
            tr td:first {
                padding-left: 5px;
            }
            tr.highlighted td {
                background-color: white;
            }
            tr.highlighted td:first-child {
                border-left: 4px solid blue;
                padding-left: 2px;
            }
            .colorIndicator {
                width: 10px;
                height: 10px;
                display: inline-block;
                float: left;
                margin-right: 5px;
            }
        </style>
{% endblock %}

{% block body %}
        <p>
            <a href="/tasks/" class="button">All</a>
            <a href="/tasks/due" class="button">Due Items Only</a>
        </p>
        <h2>Task List ({{ task_list.count }} items)</h2>
        <p>
            <a href="/tasks/add" class="button">Create New</a><br>
        </p>
        <table id="itemList">
            <tr>
                <th>Name</th>
                <th><a href="?order_by=next_date">Active</a></th>
                <th><a href="?order_by=next_due">Due</a></th>
                <th>Last Done</th>
                <th>Actions</th>
            </tr>
            {% for task in task_list %}
            <tr id="{{ task.id }}" class="{% if task.is_due %}overdue {% endif %}{% if task.is_onetime %}one-time {% endif %} task">
                <td>
                    <span class="colorIndicator">&nbsp;</span>
                    <span class="nameSpan">{{ task.name }}</span> (<span class="bold">{{ task.repeat_list_str }}</span>)<br>
                    {% for schedule in task.schedules.all %}
                        {{ schedule }}
                    {% endfor %}
                </td>
                <td>{{ task.next_date|date }}</td>
                <td>{{ task.next_due|date }}</td>
                <td>{{ task.last_done|date }}</td>
                <td>
                    <a href="/tasks/{{ task.pk }}/" class="button">Edit</a>
                    <a href="?action=delete&id={{ task.pk }}" class="button delButton">Delete</a>
                    <a href="javascript:void(null)" class="completeButton button">Post Status</a>
                </td>
            </tr>
            {% endfor %}
            <tr id="completeDialog" style="display:none">
                <td colspan="5">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ statForm }}
                        <button id="submitComplete">Post</button>
                    </form>
                </td>
            </tr>
        </table>
{% endblock %}

todo/main/templates/tasks/modify.html
{% extends "base_generic.html" %}

{% block title %}{{ obj.name }}{% endblock %}

{% block header %}
        <script type="text/javascript">
            $(function () {
                $("#discard").click(function () {
                    window.location.href="/tasks/list.html";
                });
                $("body").delegate("#submitComplete", "click", function (event) {
                    event.preventDefault();
                    $.post("", $("#completeDialog form").serialize(), function (data) {
                        if (data.indexOf("OK") == 0) {
                            // TODO: make this use another row as a template
                            $("<tr id=\"" + data.substr(2) + "\"><td>"
                                + $("#id_date").val() + "</td><td>"
                                + $("#id_text").val() + "</td><td>"
                                + ($("#id_complete").is(":checked") ? "Yes" : "") + "</td><td><a href=\"?id="
                                + data.substr(2) + "&action=rmstat\" class=\"rmstat\">rm</a></td></tr>")
                                .appendTo("#statusList");
                            $("#completeDialog form")[0].reset();
                            $("#completeDialog :input").prop("disabled", false);
                        } else {
                            alert("Invalid information!");
                        }
                    });
                    $("#completeDialog :input").prop("disabled", true);
                });
                $("body").delegate(".rmstat", "click", function (event) {
                    tr = $(this).parents("tr").first();
                    
                    $.get("rmstat", {"id": tr.attr("id")}, function (data) {
                        if (data.indexOf("OK") == 0) {
                            tr.remove();
                        } else {
                            alert("failed");
                        }
                    });
                    event.preventDefault();
                });
            });
        </script>
{% endblock %}

{% block body %}
        <h2>{% if obj %}Task {{ obj.id }} -- {{ obj.name }}{% else %}Create Task{% endif %}</h2>
        <p><span class="bold">Created:</span> {{ obj.date_created|date }}</p>
        <p><span class="bold">Due:</span> {{ obj.next_date|date }}</p>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="hidden" name="mod" value="task">
            <p>
                <input type="submit" value="Save">
                <input type="submit" name="closeafter" value="Save and Close">
                <input type="button" value="Close" id="discard">
            </p>
        </form>
        <h3>Statuses</h3>
        <table id="statusList">
            <tr>
                <th>Date</th>
                <th>Text</th>
                <th>Completed</th>
                <th>Actions</th>
            </tr>
            <tr id="completeDialog">
                <td colspan="4">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ statForm }}
                        <input type="hidden" name="mod" value="stat">
                        <button id="submitComplete">Post</button>
                    </form>
                </td>
            </tr>
            {% for status in statuses %}
            <tr id="{{ status.id }}">
                <td>{{ status.date }}</td>
                <td>{{ status.text }}</td>
                <td>{% if status.complete %}Yes{% endif %}</td>
                <td><a href="rmstat?id={{status.id}}" class="rmstat">rm</a></td>
            </tr>
            {% endfor %}
        </table>
{% endblock %}